### PR TITLE
Simon

### PR DESCRIPTION
**Pull request by simonmai**
#26 Formatted README and fixed certain steps

### CODE REVIEW

**Comment by Nbot07** [comment]
Thanks for the update Simon. It looks very nice. Could you please specify which commands didn't work and what error messages or issues you ran into when you tried to run those commands? For example, I see with ccmake that might not necessarily be installed on some systems. So maybe add the line `sudo apt-get install ccmake` to the README

**Comment by simonmai** [comment]
I updated the issue. The CMakeCache.txt file doesn't work because it was built using different sudo user "osboxes", which isn't the same for others.

**Comment by Nbot07** [comment]
Ok, so is that fixed by saving the the configuration by pressing C and then generating the configuration by pressing G when using ccmake?

**Comment by simonmai** [comment]
cmake doesn't work at all using the file. I just use cmake . to create my own CMakeCache.txt and ccmake . after to turn on the plugin and then save configuration then generate.

**Comment by Nbot07** [comment]
That seems to make sense. I think the CMakeLists file in the prototype folder must be what cmake useses to add the BUILD_PROTOTYPE flag to the CMakeCache.txt. Just to be clear, if you follow the steps of this updated readme exactly as it's written are you able to replicate what you see in the video?

**Comment by simonmai** [comment]
Yeah, I did it twice from the beginning with newly cloned repositories and it works both times. The "make" command takes too long so didn't test more.

**Review by Nbot07 — APPROVED** [review]

**Pull request merged**
